version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file: .env  # Load environment variables from .env file
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root # Use variables from .env
      PMA_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mariadb_data
